# 이름 짓기
name: Github Actions 연습하기
# 언제 이 작업을 수행할지 지정
# github에 git push할 때 수행하겠다.
on: push

# 직업 정하기
jobs:
  push-job:
    # 어디서 일할거야? -> 어떤 OS에서 일할거야?
    runs-on: ubuntu-latest
    # 구체적인 해야할 일
    steps:
      - name: 첫 번째 직업
        run: echo "첫 번쨰 작업 실행 중"

      - name: 여러 문장을 작성하기
        run: |
          echo "첫 번째 문장"
          echo "두 번째 문장"

      - name: Github Actions 자체에 저장되어 있는 변수 사용해보기
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY

      - name: Github Actions Secret 변수 사용해보기
        run: |
          echo ${{ secrets.MY_NAME }}
          echo ${{ secrets.MY_HOBBY }}
